--------------------------------------------------------
--  오라클 12c 계정 설정을 위한 세션 변경 
--------------------------------------------------------
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

--------------------------------------------------------
--  yourgg 계정 및 모든 테이블 삭제
--------------------------------------------------------
DROP USER yourgg CASCADE;

--------------------------------------------------------
--  yourgg 계정 생성
--------------------------------------------------------
CREATE USER yourgg IDENTIFIED BY root;

--------------------------------------------------------
--  yourgg 계정에 DBA 권한 부여
--------------------------------------------------------
GRANT DBA TO yourgg;

--------------------------------------------------------
--  시퀀스 생성
--------------------------------------------------------
DROP SEQUENCE "YOURGG"."BOARD_NUMBER";
CREATE SEQUENCE "YOURGG"."BOARD_NUMBER";

--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "YOURGG"."BOARD" 
   (	"BOARD_NUMBER" NUMBER, 
	"BOARD_TITLE" VARCHAR2(100 BYTE), 
	"BOARD_CONTENT" VARCHAR2(4000 BYTE), 
	"BOARD_WRITER" VARCHAR2(20 BYTE), 
	"BOARD_REGDATE" DATE, 
	"BOARD_PASSWORD" CHAR(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into YOURGG.BOARD
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOURGG"."BOARD_PK" ON "YOURGG"."BOARD" ("BOARD_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "YOURGG"."BOARD" MODIFY ("BOARD_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "YOURGG"."BOARD" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
  ALTER TABLE "YOURGG"."BOARD" MODIFY ("BOARD_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "YOURGG"."BOARD" MODIFY ("BOARD_WRITER" NOT NULL ENABLE);
  ALTER TABLE "YOURGG"."BOARD" MODIFY ("BOARD_REGDATE" NOT NULL ENABLE);
  ALTER TABLE "YOURGG"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("BOARD_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "YOURGG"."BOARD" MODIFY ("BOARD_PASSWORD" NOT NULL ENABLE);
  
  INSERT INTO "YOURGG"."BOARD" (BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, BOARD_REGDATE, BOARD_PASSWORD) VALUES ("YOURGG"."BOARD_NUMBER".NEXTVAL, '제목', '내용', '작성자', SYSDATE, '12345');
  INSERT INTO "YOURGG"."BOARD" (BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, BOARD_REGDATE, BOARD_PASSWORD) (SELECT "YOURGG"."BOARD_NUMBER".NEXTVAL, '제목', '내용', '작성자', SYSDATE, '12345' FROM "YOURGG"."BOARD");
  INSERT INTO "YOURGG"."BOARD" (BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, BOARD_REGDATE, BOARD_PASSWORD) (SELECT "YOURGG"."BOARD_NUMBER".NEXTVAL, '제목', '내용', '작성자', SYSDATE, '12345' FROM "YOURGG"."BOARD");
  INSERT INTO "YOURGG"."BOARD" (BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, BOARD_REGDATE, BOARD_PASSWORD) (SELECT "YOURGG"."BOARD_NUMBER".NEXTVAL, '제목', '내용', '작성자', SYSDATE, '12345' FROM "YOURGG"."BOARD");
  INSERT INTO "YOURGG"."BOARD" (BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, BOARD_REGDATE, BOARD_PASSWORD) (SELECT "YOURGG"."BOARD_NUMBER".NEXTVAL, '제목', '내용', '작성자', SYSDATE, '12345' FROM "YOURGG"."BOARD");
  INSERT INTO "YOURGG"."BOARD" (BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, BOARD_REGDATE, BOARD_PASSWORD) (SELECT "YOURGG"."BOARD_NUMBER".NEXTVAL, '제목', '내용', '작성자', SYSDATE, '12345' FROM "YOURGG"."BOARD");
  INSERT INTO "YOURGG"."BOARD" (BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, BOARD_REGDATE, BOARD_PASSWORD) (SELECT "YOURGG"."BOARD_NUMBER".NEXTVAL, '제목', '내용', '작성자', SYSDATE, '12345' FROM "YOURGG"."BOARD");

